version: "3.9"
services:
  web:
    image: ghcr.io/apexnova-vc/web:latest # Use the image from GitHub Container Registry
    platform: linux/arm64
    privileged: true
    build:
      context: . # Set the build context to the current directory
      dockerfile: Dockerfile # Specify the Dockerfile
      # Specify the target platform for the build
    working_dir: /com.docker.devenvironments.code # Set the working directory in the container
    volumes:
      - .:/com.docker.devenvironments.code # Mount the current directory into the working directory in the container
    environment:
      - NODE_ENV=development # Set the environment variable for development mode
