services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: ghcr.io/apexnova-vc/sample_web:latest
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
