name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set this to the node version you are using

    - name: Install Dependencies
      run: npm install

    - name: Build and Deploy
      run: npm run deploy
      env:
        CI: false
        # Personal Access Token (secrets.GH_TOKEN) should be set in the repo's secrets
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
