name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/apexnova-vc/web:latest
          ghcr.io/apexnova-vc/web:${{ github.sha }}
          ghcr.io/apexnova-vc/web:${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}
        platforms: ${{ matrix.platform }}
        cache-from: type=registry,ref=ghcr.io/apexnova-vc/web:cache
        cache-to: type=inline
