name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          apexnova-vc/sample_web:latest
          apexnova-vc/sample_web:${{ github.sha }}
        # Uncomment and modify if needed
        # build-args: |
        #   ARG_NAME=arg_value
        # platforms: linux/amd64,linux/arm64
        # cache-from: type=registry,ref=apexnova-vc/sample_web:cache
        # cache-to: type=inline
