name: ESLint Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install Dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint