name: E2E Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install Dependencies
      run: npm i

    - name: Build
      run: npm run build

    - name: Start server
      run: npx serve -s build &

    - name: Run E2E Tests
      run: npm run test:e2e